@extends('dash.layouts.app')
@section('title','CONTACTS')
@section('content')
<div class="card mb-4"><div class="card-body d-flex justify-content-between align-items-center"><div><h5 class="mb-1">{{ $label->title }}</h5><small class="text-muted">Only contacts explicitly marked opted-in can enter a broadcast queue.</small></div><div><button class="btn btn-label-danger me-2" id="is-label-delete">Delete Phonebook</button><a href="{{ route('phonebook') }}" class="btn btn-label-dark">Back</a></div></div></div>
<div class="card"><div class="card-datatable table-responsive pt-0"><table class="datatables-basic table"><thead><tr><th></th><th></th><th>Name</th><th>Number</th><th>Type</th><th>Consent</th><th>Action</th></tr></thead></table></div></div>
<div class="modal fade" id="modal-contacts-add" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">New Contact</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><form id="form-contacts-store" action="{{ route('phonebook.contacts.store',$label->id) }}" method="post">@csrf<div class="modal-body"><div class="mb-3"><label class="form-label">Name</label><input name="name" class="form-control"></div><div class="mb-3"><label class="form-label">WhatsApp Number</label><input name="number" class="form-control" required placeholder="628xxxxxxxxx"></div><div class="form-check mb-2"><input type="hidden" name="opt_in" value="0"><input class="form-check-input" type="checkbox" name="opt_in" value="1" id="optin"><label class="form-check-label" for="optin">Customer has explicitly opted in</label></div><div class="mb-3"><label class="form-label">Opt-in source</label><input name="opt_in_source" class="form-control" placeholder="Checkout checkbox / written permission / form"></div></div><div class="modal-footer"><button type="button" class="btn btn-label-secondary" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Save</button></div></form></div></div></div>
<div class="modal fade" id="modal-contacts-import" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Import XLSX</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><form id="form-contacts-import" action="{{ route('phonebook.contacts.import',$label->id) }}" method="post" enctype="multipart/form-data">@csrf<div class="modal-body"><input type="file" name="file" class="form-control" accept=".xlsx" required><div class="alert alert-info mt-3 mb-0">Imported contacts are stored as <b>consent unknown</b>. Mark consent separately before broadcasting.</div></div><div class="modal-footer"><button class="btn btn-primary">Import</button></div></form></div></div></div>
@endsection
@push('js')
<script>
(function(){const app=new velixs();const dbs=app.datatables({url:"{{ route('phonebook.contacts.ajax',$label->id) }}",url_delete:"{{ route('phonebook.contacts.delete',$label->id) }}",header:@json('PhoneBook: '.$label->title),columns:[{data:'responsive_id'},{data:'responsive_id'},{data:'name'},{data:'number'},{data:'type'},{data:'consent'},{data:'action',orderable:false,searchable:false}],btn:[{text:'<i class="ti ti-plus me-1"></i>New Contact',className:'btn btn-primary me-2',attr:{'data-bs-toggle':'modal','data-bs-target':'#modal-contacts-add'}},{extend:'collection',className:'btn btn-label-primary dropdown-toggle me-2',text:'Tools',buttons:[{text:'Import XLSX',className:'dropdown-item',attr:{'data-bs-toggle':'modal','data-bs-target':'#modal-contacts-import'}},{text:'Export XLSX',className:'dropdown-item',action:()=>location.href=@json(route('phonebook.contacts.export',$label->id))},{text:'Sync WhatsApp Contacts',className:'dropdown-item sync-whatsapp'},{text:'Sync WhatsApp Groups',className:'dropdown-item sync-groups'}]},{text:'Delete Contacts',className:'is-button-delete btn btn-label-danger'}]});
$('#is-label-delete').on('click',()=>{if(confirm('Delete this phonebook and all contacts inside it?'))app.ajax({url:@json(route('phonebook.delete',$label->id)),data:{},addons_success:()=>location.href=@json(route('phonebook'))})});
$(document).on('click','.sync-whatsapp',()=>app.ajax({url:@json(route('phonebook.contacts.syncwhatsapp',$label->id)),data:{},addons_success:()=>dbs.ajax.reload()}));
$(document).on('click','.sync-groups',()=>app.ajax({url:@json(route('phonebook.contacts.fetchgroup',$label->id)),data:{},addons_success:()=>dbs.ajax.reload()}));
$(document).on('click','.set-consent',function(){const id=this.dataset.id,status=this.dataset.status;let source='';if(status==='opted_in'){source=prompt('Catat sumber izin customer (contoh: checkout checkbox / form / written permission):','');if(!source)return;}if(status==='opted_out'&&!confirm('Tandai contact ini sebagai opted-out?'))return;const url=@json(route('phonebook.contacts.consent','__ID__')).replace('__ID__',id);app.ajax({url,data:{status,source},addons_success:()=>dbs.ajax.reload()});});
$('#form-contacts-store').on('submit',function(e){e.preventDefault();app.ajax({url:this.action,data:$(this).serialize(),addons_success:()=>{$('#modal-contacts-add').modal('hide');this.reset();dbs.ajax.reload()}})});
$('#form-contacts-import').on('submit',function(e){e.preventDefault();const form=this;$.ajax({url:form.action,type:'POST',headers:{'X-CSRF-TOKEN':$('meta[name=csrf-token]').attr('content')},data:new FormData(form),contentType:false,processData:false,success:r=>{app.swal_success({message:r.message});$('#modal-contacts-import').modal('hide');form.reset();dbs.ajax.reload()},error:r=>app.swal_error({message:r.responseJSON?.message||'Import failed'})})});})();
</script>
@endpush
@push('cssvendor')<link rel="stylesheet" href="{{ asset('assets/vendor/libs/datatables-bs5/datatables.bootstrap5.css') }}" /><link rel="stylesheet" href="{{ asset('assets/vendor/libs/datatables-responsive-bs5/responsive.bootstrap5.css') }}" /><link rel="stylesheet" href="{{ asset('assets/vendor/libs/datatables-buttons-bs5/buttons.bootstrap5.css') }}" />@endpush
@push('jsvendor')<script src="{{ asset('assets/vendor/libs/datatables-bs5/datatables-bootstrap5.js') }}"></script>@endpush
